**************************************************************
*                  EKHM66 Fall 2020                          *
*     Lab 5: Fixed Effects and Difference-In-Differences     *
**************************************************************

/*TIP: EXECUTE COMMANDS FROM THE DO-FILE BY HIGHLIGHTING THE COMMANDS AND PRESSING CTRL+D.
PRESS THE PAGE UP KEY TO RETRIEVE THE MOST RECENTLY EXECUTED COMMAND TO THE COMMAND WINDOW.*/

* IN THIS LAB, WE LOOK AT TWO METHODS THAT ARE USED TO TRY AND ACCOUNT FOR VARIOUS BIASES 
* WHEN WE CANNOT FIND A SUITABLE INSTRUMENT OR A DISCONTINUITY TO EXPLOIT: FIXED EFFECTS AND DIFFERENCE-IN-DIFFERENCES.
* FE AND DIF-IN-DIF ARE LESS EFFICIENT THAN A WORKING IV OR RD, SINCE FE AND DIF-IN-DIF CAN ONLY ACCOUNT FOR BIAS THAT DOES NOT VARY OVER A CHOSEN DIMENSION, SUCH AS TIME OR SPACE. 
* FINDING IV:S AND RD:S IS HARD, SO THE METHODS IN THIS LAB HAVE BEEN COMMONLY USED IN RECENT YEARS.


***1. FIXED EFFECTS***

* FIXED EFFECTS ESTIMATION EXPLOITS THAT SOME CHARACTERISTICS OF A UNIT ARE FIXED IN TIME, SPACE OR SOME OTHER DIMENSION (FOR EXAMPLE, A FAMILY).
* IT IS A WAY TO TRY AND GET RID OF SOME VARIATION THAT IS INDIVIDUAL AND THEREBY GET US CLOSER TO A CAUSAL EFFECT OF AN EXPLANATORY VARIABLE.

* IN THIS LAB, WE EXPLOIT PANEL DATA (WHICH MEANS THAT WE HAVE MULTIPLE OBSERVATIONS PER INDIVIDUAL) TO GET RID OF SELECTION BIAS.
* WE USE DATA FROM THE PANEL STUDY OF INCOME DYNAMICS (PSID).
* IT IS A SOCIO-ECONOMIC PANEL FROM THE U.S., FOLLOWING INDIVIDUALS OVER 7 YEARS (1976-1982).

* THE RESEARCH QUESTION IS: WHAT IS THE CAUSAL EFFECT OF UNION MEMBERSHIP ON WAGES?

cd "\\uwfpcluster01.uw.lu.se\el8285la$\Documents\PhD programme\Teaching\EKHM66 Econometrics II, Ht 2020\Labs\Lab 5 (Fixed effects and Difference-in-differences)"

log using "lab5.log", replace

use "mus08psidextract.dta", clear


* LET'S HAVE A LOOK AT THE DATA:
describe
br
* WE CAN SEE THAT EVERY INDIVIDUAL (column: id) HAS SEVERAL OBSERVATIONS IN TIME (column t)

* IN THIS PARTICULAR CASE, WE FOCUS ON MEN
drop if fem==1 


* AN EXAMPLE OF THE WAGE OF INDIVIDUAL 1 OVER TIME:
graph twoway line lwage t if id==1

* IN STATA, WE HAVE A SPECIAL PACKAGE FOR PANELS CALLED xt. 
* WE START BY TELLING STATA THAT OUR DATASET IS A PANEL BY:
xtset id t
* WHERE THE LOGIC IS: xtset panelvariable timevariable
* OUR PANEL-VARIABLE IS THE UNIT OF OBSERVATION, WHICH HERE IS A PERSON BUT CAN ALSO BE A CITY, COUNTRY, FIRM OR SOMETHING ELSE.
* OUR TIME-VARIABLE IS THE TIMESTAMP IN THE DATA - YEAR IS COMMON BUT IT CAN ALSO BE, LIKE IN THIS CASE, JUST AN NUMBER (BUT WE KNOW, BY KNOWING THE DATA, THAT THESE ARE YEARS).

* xtset TELLS US THAT WE HAVE A "STRONGLY BALANCED" PANEL.
* THIS MEANS WE HAVE NO MISSING OBSERVATIONS FOR INDIVIDUALS - EVERY INDIVIDUAL IS OBSERVED EVERY YEAR.
* IN AN UNBALANCED PANEL, INDIVIDUALS ARE OBSERVED A DIFFERENT NUMBER OF TIMES (OBSERVATIONS ARE MISSING). 
* IF THIS IS THE CASE, LOOK CLOSER INTO WHY OBSERVATIONS ARE MISSING.
* IF THEY ARE NOT MISSING COMPLETELY AT RANDOM, THIS MIGHT BIAS THE RESULTS AND WE NEED TO DISCUSS IT IN OUR RESEARCH.

* WE CAN NOW EXPLORE THE PANEL:
xtdescribe
* WE HAVE 528 INDIVIDUALS, EACH OBSERVED FOR 7 YEARS.


***WITHIN AND BETWEEN INDIVIDUAL VARIATION***

* WE CAN LOOK AT THE WITHIN-BETWEEN DYNAMIC FOR ALL THE VARIABLES IN THE DATASET:
xtsum
* N STANDS FOR PERSON-OBSERVATIONS, n FOR PERSONS, AND T FOR NUMBER OF TIME PERIODS.
* THE "BETWEEN" VARIANCE CAN BE DESCRIBED AS "HOW MUCH ARE PEOPLE DIFFERENT FROM EACH OTHER?"
* THE "WITHIN" VARIANCE CAN BE DESCRIBED AS "HOW MUCH ARE PEOPLE DIFFERENT FROM THEMSELVES OVER TIME?" 
* THIS MAY BE AWKWARDLY PUT. THE IDEA IS TO DESCRIBE THE EXTENT TO WHICH INDIVIDUALS CHANGE STATUS ON A VARIABLE OVER TIME.

* LOOKING AT THE MARITAL STATUS (ms) VARIABLE (0-1), THE OVERALL AVERAGE (overall) IS 0.91. THIS IS FOR THE PERSON-OBSERVATIONS.
* THIS IS THE SAME VALUE YOU WOULD GET USING THE summarize COMMAND, WITHOUT TAKING INTO ACCOUNT THE PANEL STRUCTURE.

* THE between ROW SHOWS THE STANDARD DEVIATION OF THE SQUARED DIFFERENCES BETWEEN EACH PERSON'S "MEAN MARRIAGE STATUS" OVER TIME AND THE overall MEAN.
* IF EVERY PERSON HAD THE EXACT SAME PATTERN (FOR EXAMPLE, FIRST THREE YEARS MARRIED, LAST FOUR YEARS DIVORCED), 
* THIS ROW WOULD BE 0 (HIGHLY UNLIKELY FOR AN INDIVIDUAL-LEVEL VARIABLE).
* IF A TIME-DEPENDENT MACRO VARIABLE, SUCH AS YEARLY UNEMPLOYMENT RATE, IS INCLUDED (AND THE SAME FOR ALL RESPONDENTS), 
* IT WOULD ALSO GIVE A ZERO ON THIS ROW (SINCE NOTHING VARIES BETWEEN INDIVIDUALS).

* THE within ROW SHOWS THE STANDARD DEVIATION OF THE SQUARED DIFFERENCES BETWEEN EACH PERSON'S STATUS 
* AT EACH TIME POINT OVER TIME AND THE SAME PERSON'S "MEAN MARRIAGE STATUS"
* A PERSON THAT IS MARRIED OR UNMARRIED DURING ALL YEARS WILL HAVE ZERO ON THIS ROW.

* IF between IS HIGHER THAN within, IT MEANS IT IS MORE COMMON FOR PEOPLE DEVIATE FROM EACH OTHER ("EITHER MARRIED OR UNMARRIED FOR MOST OF THE TIME") 
* THAN PEOPLE DEVIATING FROM THEIR OWN STATUS ("PEOPLE MARRY AND DIVORCE ALL THE TIME").
* NOTE ALSO THAT TIME-INVARIANT VARIABLES (RACE, FOR EXAMPLE) HAVE NO WITHIN-VARIATION, SINCE THIS DOES NOT CHANGE OVER TIME.
* WAGE IS A VARIABLE THAT HAS PLENTY OF VARIANCE BOTH WITHIN AND BETWEEN INDIVIDUALS.


* WITH THE xt FORMAT, WE CAN MAKE GRAPHS OVER TIME:
xtline lwage if id<=5 // WAGE GRAPH FOR FOUR FIRST INDIVIDUALS OF THE PANEL
* OR WE CAN PUT THEM ALL IN THE SAME GRAPH
xtline lwage if id<=5, overlay


***POOLED OLS***

* CAN WE TRY AND ANSWER THE RESEARCH QUESTION USING A REGULAR OLS? 
* REMEMBER, THAT THIS IS NOT A CROSS-SECTION, BUT ONE INDIVIDUAL APPEARS MANY TIMES!

gen exp2 = exp^2 // GENERATE SQUARED WORK EXPERIENCE TO ACCOUNT FOR NON-LINEARITY

reg lwage exp exp2 wks ed union ind occ 
* WHEN WE RUN A STANDARD OLS MODEL ON A PANEL, WE CALL THIS A "POOLED OLS" REGRESSION.
* THIS IS BECAUSE THE REPEATEDNESS OF INDIVIDUALS IS NOT ACKOWLEDGED, THE OBSERVATIONS ARE ALL IN THE SAME POOL OF OBSERVATIONS.


* THERE ARE TWO MAIN PROBLEMS WITH POOLED OLS:

* 1. WE ARE NOT ACCOUNTING FOR INDIVIDUAL HETEROGENEITY = SELECTION PROBLEM.

* EVEN THOUGH WE TRY AND CONTROL FOR AS MANY THINGS AS POSSIBLE, THERE WILL PROBABLY BE INDIVIDUAL DIFFERENCES BETWEEN PEOPLE THAT ARE NOT CAPTURED BY OUR COVARIATES.
* IN THE CASE OF THIS RESEARCH QUESTION, IT IS LIKELY THAT BOTH MORE ABLE, GO-GETTING INDIVIDUALS MIGHT JOIN THE UNION TO A GREATER EXTENT.
* BUT IT'S ALSO NOT UNREASONABLE THAT LESS ABLE AND WAGE-SECURITY SEEKING INDIVIDUALS ARE MORE LIKELY TO JOIN THE UNION.

* SINCE ABILITY ALSO AFFECTS AN INDIVIDUAL'S EARNINGS POTENTIAL, WE CLEARLY CANNOT GET TO THE CAUSAL EFFECT OF UNION MEMBERSHIP ON WAGES USING A POOLED OLS.
* WE HAVE NO IDEA ABOUT WHICH DIRECTION OUR UNOBSERVABLES ARE BIASING THE RESULTS.

* 2. THE ERRORS (I.E. WHAT WE ARE NOT CONTROLLING FOR) ARE SERIALLY CORRELATED OVER TIME.

* FOR EXAMPLE, ONE PERSON'S ABILITY AT TIME T WILL BE HIGHLY CORRELATED WITH THE ABILITY IN T-1.
* SERIAL CORRELATION OF ERRORS WILL NOT BIAS THE RESULT, BUT IT WILL MAKE THE STANDARD ERRORS UNRELIABLE.
* IT CAN LEAD TO WRONG CONCLUSIONS ABOUT THE PREDICTIVE POWER OF THE MODEL.
* WE THINK THAT THE PREDICTION IS BETTER THAN IT ACTUALLY IS (WE MAY WRONGLY REJECT NULL HYPOTHESIS).

* IF WE KNOW THE SOURCE OF SERIAL CORRELATION (INDIVIDUAL IN THIS CASE), WE CAN ADJUST FOR IT USING CLUSTERED STANDARD ERRORS:
reg lwage exp exp2 wks ed union ind occ, vce(cluster id)

* IN SUM, WE CAN SOLVE PROBLEM 2 BY USING CLUSTERED STANDARD ERRORS, BUT PROBLEM 1 CANNOT BE SOLVED IN A POOLED OLD SETTING.


***FIXED EFFECTS***

* THE NATURE OF PANEL DATA IS USEFUL WITH REGARD TO SELECTION BIAS.
* IF OUR PROBLEMATIC UNOBSERVABLE VARIABLE (ABILITY) IS ROUGHLY THE SAME FOR AN INDIVIDUAL OVER TIME, 
* WE CAN REMOVE THIS SOURCE OF BIAS BY LOOKING AT VARIATION WITHIN INDIVIDUALS ONLY.
* THE WAY TO THINK ABOUT THIS IS: A PERSON IS LIKELY TO BE ROUGHLY THE SAME OVER TIME, 
* SO IF WE LOOK AT OUTCOMES BEFORE AND AFTER THE SAME PERSON HAS JOINED THE UNION, THE WAGE EFFECTS SHOULD NOT BE BECAUSE OF CHANGES IN UNOBSERVED ABILITY.
* "IF YOU'RE YOURSELF OVER TIME, THE EFFECT OF YOU JOINING THE UNION ON YOUR WAGE SHOULD BE CAUSAL - FOR YOU."
* SINCE WE HAVE MANY INDIVIDUALS, WE CAN LOOK AT THE AVERAGE EFFECT ON THE INDIVIDUALS WHO JOINED.

* THE FIXED EFFECTS ESTIMATOR IS ALSO CALLED THE "WITHIN ESTIMATOR".
* WE ARE, BY USING FIXED EFFECTS, GETTING RID OF PROBLEMATIC "BETWEEN" VARIATION.

* THE IDEA WITH FIXED EFFECTS IS TO CONTROL AWAY FACTORS THAT DO NOT CHANGE OVER TIME (OR, IN OTHER SETTINGS, OVER SPACE, OR WITHIN A FAMILY)
* IT IS NOT AS STRONG OF A METHOD THAN USING A  EXPERIMENT OR A GOOD INSTRUMENT, BUT IN MANY CASES THE ASSUMPTIONS ARE NOT TOO FAR-FETCHED.

* WE ACCOUNT FOR INDIVIDUAL EFFECTS BY RUNNING:
xtreg lwage exp exp2 wks ed union ind occ, fe // THE OPTION fe ADDS FIXED EFFECTS ON THE PANEL LEVEL THAT WE DEFINED IN xtset

* THE FIXED EFFECTS WORK AS IF EVERY PERSON HAD THEIR OWN DUMMY VARIABLE. 
* THE xtreg USES A MORE EFFICIENT WAY TO DIFFERENCE OUT INDIVIDUAL EFFECTS, WITHOUT CALCULATING THE INDIVIDUAL DUMMIES.


* LET'S COMPARE THE RESULTS FROM THE POOLED OLS WITH THE FE REGRESSION:
reg lwage exp exp2 wks ed union ind occ, cl(id)
eststo pooled
xtreg lwage exp exp2 wks ed union ind occ, fe
eststo fe

esttab pooled fe 

* WHEN WE HAVE A LOG-LIN MODEL (DEPENDENT VARIABLE IS LOG TRANSFORMED, REGRESSOR NOT), WE HAVE TO EXPONENTIATE THE ESTIMATED COEFFICIENT FOR THE REGRESSOR.
* STATA CAN DO THIS FOR US:
	* UNION STATUS, POOLED OLS 
		display exp(.1204051) // FIGURE IN PARENTHESES IS THE COEFFICIENT OF union
		* WE GET ≈ 1.128.
		* THE ESTIMATED PERCENTAGE CHANGE IN THE OUTCOME VARIABLE AS REGRESSOR INCREASES BY ONE UNIT IS THE FIGURE ABOVE MINUS 1.00.
		* BEING A UNION MEMBER IN ASSOCIATED WITH 12 % HIGHER WAGES, WHICH HAS TO BE CONSIDERED SUBSTANTIAL.
	* UNION STATUS, FIXED EFFECTS
		display exp(.0316998) // FIGURE IN PARENTHESES IS THE COEFFICIENT OF union
		* WE GET ≈ 1.032.
		* JOINING A UNION IN ASSOCIATED WITH A 3 % INCREASE IN WAGES, WHICH IS A LOT LESS THAN WITH THE OLS ESTIMATE.
		* THIS ESTIMATE IS BASED ON VARIATION ONLY FROM THOSE INDIVIDUALS WHO CHANGED THEIR UNION MEMBERSHIP STATUS DURING THE PANEL.

* THIS IS VERY OFTEN THE CASE: WHEN WE CONTROL FOR INDIVIDUAL FIXED EFFECTS, EFFECT SIZES BECOME A LOT SMALLER.
* ONE EXPLANATION IS THAT WE MANAGED TO CAPTURE THE SELECTION BIAS, AND IT WAS POSITIVE.
* THE POOLED OLS WOULD HAVE BEEN OVERESTIMATING THE EFFECT OF UNION MEMEBERSHIP BECAUSE MORE ABLE PEOPLE OPTED TO JOIN.

* BUT! WE NEED TO BE CAREFUL WHEN INTERPRETING FE RESULTS.
* BECAUSE THEY ARE BASED ON AVERAGES OF WITHIN-INDIVIDUAL VARIATION, THEY ARE ALSO VERY SENSITIVE TO MEASUREMENT ERROR.
* AND, EVEN THOUGH FE IS A POPULAR METHOD, IT IS OFTEN ACCUSED OF THROWING OUT THE BABY OUT WITH THE BATHWATER.
* THAT IS, YES, IT MIGHT BE TAKING CARE OF PROBLEMATIC VARIATION, BUT IT IS ALSO REMOVING GOOD VARIATION.
* ALSO, THERE MAY BE EXTERNAL VALIDITY PROBLEMS, SINCE YOU ONLY CONSIDERING THE "CHANGERS", WHICH MIGHT BE A SELECTED GROUP.
* AND, BY DESIGN OF THE FIXED EFFECTS FRAMEWORK, WE ONLY ACCOUNT FOR UNOBSERVED FACTORS THAT ARE TIME-INVARIANT.
* THERE MAY STILL BE UNOBSERVED, TIME-VARIANT FACTORS THAT INFLUENCE OUR ESTIMATES.


* A NOTE ON CLUSTERED STANDARD ERRORS IN PANEL MODELS: 
	* IT'S HARD TO GET A STRAIGHT ANSWER IN THE LITERATURE FOR THE QUESTION: SHOULD I CLUSTER MY STANDARD ERRORS WHEN I HAVE A PANEL AND INDIVIDUAL FIXED EFFECTS?
	* IT'S NOT EASY TO FIND ANY RULE OF THUMB, BUT HERE IS A LINK TO A DISCUSSION: https://www.statalist.org/forums/forum/general-stata-discussion/general/1347828-cluster-standard-errors_-fixed-effect
	* SO, IT'S A GOOD IDEA TO THINK ABOUT WHETHER CLUSTERING IS NEEDED OR NOT. 
	* DO NOT EMPHASISE P-VALUES TOO MUCH.
	* FOR THIS COURSE, DO NOT WORRY ABOUT IT - "REGULAR" STANDARD ERRORS WILL DO.


***2. DIFFERENCES-IN-DIFFERENCES***

* THE DIF-IN-DIF APPROACH MAKES USE OF THE FACT THAT IT IS NOT UNCOMMON FOR (AGGREGATE) STUDY UNITS (FOR EXAMPLE, REGIONS AND CITIES) TO HAVE THE SAME TRENDS FOR PERIODS OF TIME. 
* BY IDENTIFYING A TREATMENT BETWEEN TWO UNITS AT A CERTAIN POINT IN TIME, IT IS POSSIBLE TO GET TO THE TREATMENT EFFECT LOOKING AT TRENDS AFTER TREATMENT.
* DIF-IN-DIF CAN BE THOUGHT OF AS A "FIXED EFFECTS FOR AGGREGATE UNITS".

* WE USE DATA FROM THE COURSE BOOK, SHOWING THE METHOD APPLIED TO THE MISSISSIPPI BANKING CRISIS OF THE 1930S (RICHARDSON & TROOST 2009).
* THE FEDERAL RESERVE DISTRICTS 6 (ATLANTA) AND 8 (ST. LOUIS) HAD VERY DIFFERENT METHODS OF HANDLING FAILING BANKS.
* ATLANTA WAS IN FAVOR OF HELPING BANKS SURVIVE, WHILE ST. LOUIS WAS STRICTLY NON-INTERVENTION.
* ACCORDING TO RICHARDSON AND TROOST, DIFFERENCES IN POLICY WERE ADOPTED WELL BEFORE THE CRISIS. 
* THEY ARGUE THAT THIS DIFFERENCE CAN BE EXPLOITED AS AN "EXOGENOUS POLICY EXPERIMENT" (P. 1033 IN ARTICLE).
* THE "EXPERIMENT" CONSISTS OF ST. LOUIS BANKS AS THE CONTROL GROUP AND ATLANTA BANKS AS THE TREATMENT GROUP.

* THE TWO DISTRICTS ARE NOT IDENTICAL: FOR EXAMPLE, THERE ARE AN UNEQUAL AMOUNT OF BANKS BETWEEN THEM).
* BUT THIS IS NOT A PROBLEM, AS THE DIF-IN-DIF METHOD IS FOCUSED ON TRENDS, NOT LEVELS.


***LOADING DATA***

use banks.dta, clear

* THE IDENTIFYING ASSUMPTION OF THE DIF-IN-DIF METHOD IS THE PARALLELL TREND ASSUMPTION. 
* "WHAT HAPPENED IN ST. LOUIS IS WHAT WOULD HAVE HAPPENED IN ATLANTA, HAD IT NOT BEEN TREATED."
* IN ORDER TO BE ABLE TO MAKE THIS ARGUMENT, WE SHOULD LOOK CLOSER AT THE TRENDS BEFORE TREATMENT.

* LETS GRAPH THE BANKS IN BUSINESS AND BANKS IN OPERATION OVER TIME.
* WE ADD STRAIGHT LINES TO THE DATES OF THE CALDWELL CRASH AND ST. LOUIS ADOPTING POLICIES LIKE ATLANTA.
* TO USE THE TIME DIMENSION OF THE DATA FRO GRAPHING, WE SPECIFY tsset timevariable, daily.
* daily TELLS STATA THAT THE TIME VARIABLE IS GIVEN FOR EACH DAY.

tsset date, daily

graph twoway tsline bib6 bio6 bib8 bio8, tline(14nov1930 31jul1931)
* STATA USES THE TIME VARIABLE WE JUST SPECIFIED AS THE X-AXIS VARIABLE.
* USING THE tsline GRAPH OPTIONS ALLOWS US TO USE THE DATES IN THEIR CURRENT FORMAT (NO CONVERSION TO NUMERICAL NEEDED).

* DO WE HAVE A PARALLELL TREND BEFORE TREATMENT (CALDWELL CRASH)?


* LET'S CREATE THE COUNTERFACTUAL DEVELOPMENT (WHAT WOULD THE TRENDS LOOK LIKE IF THE UNTREATED HAD BEEN TREATED?).
* SEE THE PAPER FOR DETAILED EXPLANATION OF THE METHOD.
* WE ONLY KEEP MID-YEAR OBSERVATIONS (1ST OF JULY EACH YEAR):
keep if month==7 & day==1
*THIS GIVES US A VERY SMALL SAMPLE, BUT IF THE ASSUMPTIONS HOLD, IT IS ENOUGH.
graph twoway tsline bib6 bio6 bib8 bio8 

* OUR COUNTERFACTUAL CONSISTS OF:
gen diff=bib8-bib6
* DIFFERENCE IN SURVIVING BANKS BETWEEN TREATED (ATLANTA) AND UNTREATED (ST.LOUIS)
* THIS IS THE DIFFERENCE THAT WE ACTUALLY OBSERVED

gen bibc=bib6*(year==1929)+(bib8-diff[2])*(year>=1930) 
* THIS IS THE COUNTERFACTUAL TREND FOR TREATED (ATLANTA) IF THEY HAD NOT BEEN TREATED, 
* ASSUMING THEIR TREND WOULD HAVE BEEN THE SAME AS THAT OF THE UNTREATED (ST. LOUIS) GROUP.
* FIRST YEAR OF THE COUNTERFACTUAL TREND, 1929, IS THE SAME AS NORMALLY (BECAUSE WE CAN OBSERVE IT). 
* WE JUST TAKE THE VALUE FOR bib6 FROM THE CELL OF YEAR 1929 (year==1929)).
* THEN, WE GENERATE THE COUNTERFACTUAL TREND FOR ATLANTA AFTER THE CALDWELL CRASH (year>=1930).
* YEARS FOLLOWING THE CALDWELL CRASH ARE VALUES FROM THE UNTREATED (ST. LOUIS) GROUP, MINUS THE OBSERVED DIFFERENCE FROM 1930 (diff[2]).

* GRAPHING THE DATA AND THE ASSUMED COUNTERFACTUAL DEVELOPMENT (THE bibc LINE) 
* (FIGURE 5.3 IN ANGRIST & PISCHKE)
tsline bib6 bib8 bibc

* THE ASSUMED TREATMENT EFFECT IS DEPICTED IN FIGURE 5.1
* THIS PIECE OF CODE IS A LITTLE COMPLICATED, BUT IT'S HERE TO SHOW YOU HOW THE GRAPH CAN BE REPLICATED
scatter bib8 bib6 bibc year if year > 1929 & year < 1932, msymbol(circle circle circle) msize(vlarge vlarge vlarge) ///
mcolor(black black black) connect(l l l)  lpat(l l -) lwidth(medium medthick medium) lcolor(black black black) ///
xscale(range(1929 1932)) yscale(range(95 170)) xlabels(#4) legend(off) ytitle("Number of Banks in Business") 
* THE ASSUMED TREATMENT EFFECT IS THE DIFFERENCE BETWEEN THE DOTTED AND SOLID LINE.
* WE ARE NOW DONE WITH THE VISUAL EXAMINATION OF OUR DATA AND MOVE ON TO REGRESSION ANALYSIS.


* OUR DEPENDENT VARIABLE IS THE NUMBER OF BANKS.
* WE NEED DUMMIES FOR TREATED (I.E. ATLANTA) AND POST CALDWELL CRASH (>1930).
* THE DATA ARE IN WIDE FORMAT, BUT WE WANT IT IN LONG FORMAT.
* WE DO SOME TRICKS TO TRANSFORM THE FORMAT.

expand 2 // WE DUPLICATE THE DATA SO WE GET EVERY YEAR TWICE

gen treated=1 if _n<7 // WE GENERATE A TREATMENT DUMMY AND SELECT THE FIRST 7 OBSERVATIONS.
* WE COULD ALSO HAVE TAKEN THE LAST 7 - THIS IS JUST TO SEPARATE OBSERVATIONS FOR ATLANTA AND ST. LOUIS.
replace treated=0 if treated==.
* NOTE THAT THIS TREATMENT DUMMY ALSO CAN BE REGARDED AS A STATE FIXED EFFECT.

gen banks=. // THIS IS A COLUMN KEEPING OUR OUTCOME VARIABLE
replace banks=bib6 if treated==1 // WE PUT THE ATLANTA BANKS HERE (TREATED)
replace banks=bib8 if treated==0 // AND THE ST LOUIS BANKS HERE (UNTREATED)

gen post=1 if year>1930 
replace post=0 if year<1931 // THIS IS OUR DUMMY FOR POST-CALDWELL-CRASH

* WE CAN DROP UNNECESSARY VARIABLES
drop weekday day month bib6 bio6 bib8 bio8 date diff bibc 

*NOW, WE HAVE THE BARE-BONES DATA TO DO THE DIF-IN-DIF REGRESSION:
br

*THEN WE RUN THE REGRESSION MODEL GIVEN BY THE EQUATION ON PAGE 188 IN ANGRIST & PISCHKE:
reg banks i.treated i.post i.treated##i.post

* HERE, OUR DIF-IN-DIF ESTIMATE IS THE INTERACTION TERM.
* THAT IS, AROUND 21 BANKS WERE SAVED BY THE TREATMENT.
* NOTE ALSO THAT THE i.treated DUMMY IS ALSO AN "INDIVIDUAL FIXED EFFECT" FOR ATLANTA
* (DIFFERENCE IN LEVELS OF BANKS BETWEEN ATLANTA AND ST. LOUIS IN 1929).



* THE MOST IMPORTANT THING FOR A DIF-IN-DIF IS THE PARALLELL TREATMENT ASSUMPTION.
* IF IT DOES NOT HOLD, THE WHOLE EXERCISE IS USELESS. 
* THERE IS NO FORMAL TEST OF THIS ASSUMPTION, BUT IT NEEDS TO BE SHOWN IN GRAPHS AND ARGUED VERBALLY USING THE PRE/POST EVENT DATA.
* IF YOU HAVE BIGGER DATASETS THAN THE ONE USED HERE, THE ISSUE OF SERIAL CORRELATION ALSO NEEDS TO BE CONSIDERED.
* I.E. USE CLUSTERED STANDARD ERRORS.
