**********************************************************************
*                                                                    *
*    LAB 6: ASSUMPTIONS, TRANSFORMATIONS, PRESENTATION OF RESULTS    *
*                                                                    *
**********************************************************************

************SECTION I. LOAD DATA AND PREPARE DATASET AS IN PREVIOUS LAB***************

/*
IN THIS SECTION WE WILL BE USING THE CURRENT POPULATION SURVEY FROM MARCH, 2012 CONDUCTED 
BY THE U.S. CENSUS BUREAU. THIS DATASET IS MUCH LARGER THAN THE LAST ONE WE USED, 
BUT EVERYTHING WE LEARNED BEFORE STILL APPLIES.
THE EXTRACTION INCLUDES ONLY INDIVIDUALS AGE 18 TO 65.
*/
clear all
cd "C:\Users\en8215de\OneDrive - Lund University\EKHM65_Econometrics1\2019\lab6_2019"
use "lab6_2019_income.dta", clear

drop if inctot<0

bysort serial: gen adultsinhh=_N
label var adultsinhh "Number of aduts in household"

tab adultsinhh

tab indly
gen industryflag= (indly==0)
tab industryflag
drop if industryflag==1
drop industryflag

gen sector=.
replace sector=1 if indly>1 & indly<=500
replace sector=2 if indly>500 & indly<4000
replace sector=3 if indly>4000
label define sector_lbl 1 "primary" 2 "secondary" 3 "tertiary"
label val sector sector_lbl 
label var sector "Job sector categories"
tab sector

gen race_cat=. 
replace race_cat=1 if race==100
replace race_cat=2 if race==200
replace race_cat=3 if race==300
replace race_cat=4 if race>=650 & race<=652
replace race_cat=5 if race>652
label define race_cat_lbl 1 "White" 2 "African American" 3 " Native American" 4 " Asian/Pacific Islander" 5 "two or more races"
label val race_cat race_cat_lbl
label var race_cat "Racial categories"
tab race_cat

gen edu_cat= .
replace edu_cat=1 if educ99<10
replace edu_cat=2 if educ99==10
replace edu_cat=3 if educ99>10 & educ99<15
replace edu_cat=4 if educ99==15
replace edu_cat=5 if educ99==16
replace edu_cat=6 if educ99>16 & educ99!=. 
label define educ 1 "less than HS diploma" 2 "HS Diploma" 3 "Some college/Associates Degree" 4 "Bachelor's Degree" 5 "Master's Degree" 6 "Ph.D. or Professional", replace
label val edu_cat educ
label var edu_cat "Education categories"
tab edu_cat

tab sex, summarize(inctot)
tab race_cat, summarize(inctot)
tab sector, summarize(inctot)
tab edu_cat, sum(inctot)

gen income_flag= (inctot>200000)

codebook empstat
gen employed= (empstat<14)



*************ASSUMPTIONS CHECKS************
{
***HETEROSKEDASTICITY TESTS***
reg inctot age i.race_cat i.sector i.disabwrk if employed==1 & income_flag==0
rvfplot
predict e, res
predict yhat

twoway scatter e yhat

*BREUSCH-PAGAN TEST
estat hettest

*WHITE'S TEST
estat imtest, white

*BOTH TESTS SEEM TO INDICATE THAT HETEROSKEDASTICITY IS A PROBLEM.
*HO: HOMOSKEDASTICITY

*IT'S GOOD PRACTICE TO USE BOTH OF THESE TESTS, AS THEY WORK IN DIFFERENT WAYS AND HAVE DIFFERENT PROPERTIES.
*TYPICALLY, I WOULD RECOMMEND USING THE RESULTS OF MULTIPLE TESTS AS WELL AS GRAPHS TO DRAW YOUR OWN CONCLUSIONS. 
*ALSO, NOTE THAT THESE TESTS HAVE BETTER LARGE SAMPLE PROPERTIES AND WORK WORSE IN SMALL SAMPLES.


***NORMALITY OF RESIDUALS***

hist e if employed==1 & income_flag==0, norm

sktest e if employed==1 & income_flag==0

/*
YOU WILL NOTICE THAT THE SKTEST DOES NOT GIVE US ANY P-VALUES OR CHI2 STATISTICS!
THIS IS BECAUSE -SKTEST- AUTOMATICALLY ADJUSTS FOR SAMPLE SIZE IN SMALL SAMPLES.
CLEARLY OUR SAMPLE IS APPROACHING INFINITY, AND THUS WE SHOULD SPECIFY THE -NOADJUST- OPTION.
*/

sktest e if employed==1 & income_flag==0, noadjust

/*
WE SEE HERE THAT HETEROSKEDASTICITY IS DEFINITELY A PROBLEM.
IT IS OBVIOUS FROM THE SCATTER PLOT AND THE WHITE TEST AND BREUSCH PAGAN CONFIRM IT.
OUR RESIDUALS ARE NON-NORMAL ACCORDING TO BOTH THE HISTOGRAM AND SKEWNESS-KURTOSIS TEST.
*/

***MULTICOLLINEARITY***

* TO CHECK FOR MULTICOLLINEARITY, WE SHOULD CHECK THE VIF(VARIANCE INFLATION FACTOR).
vif 
*RULE OF THUMB: IF VIF > 5, COLLINEARITY MAY BE A PROBLEM.
*IN THIS CASE ONLY OUR CATEGORICAL VARIABLE HAS A VIF LARGER THAN 5, BUT THIS IS NOTHING TO BE WORRIED ABOUT
*1/VIF TELLS US WHAT PROPORTION OF AN X VARIABLE'S VARIANCE IS INDEPENDENT OF ALL THE OTHER X VARIABLES
*VIF REFLECTS THE DEGREE TO WHICH OTHER COEFFICIENTS' VARIANCES AND se ARE INCREASED DUE TO THE INCLUSION OF THAT PREDICTOR. 
*PAIRWISE CORRELATIONS ("pwcorr") CAN ALSO BE USED TO TEST FOR MULTICOLLINEARITY, BUT SINCE WE ARE USING CATEGORICAL VARIABLES IT DOES NOT MAKE THE MOST SENSE


/*
OUR MODEL SUFFERS FROM HETEROSKEDASTICITY AND NON-NORMAL RESIDUALS.  MULTICOLLINEARITY DOES NOT SEEM TO BE AN ISSUE.
THIS IS TYPICAL WHEN WORKING WITH LARGE DATASETS, AND CAN EASILY BE CORRECTED.
THE NON-NORMAL ERRORS SHOULD NOT BE AN ISSUE.  THEY DO NOT VIOLATE THE OLS ASSUMPTIONS AND BY GRAPHICAL EXAMINATION, IT APPEARS THAT THE DISTRIBUTION IS FAIRLY CLOSE TO NORMAL.
THE REJECTION OF THE NULL IN OUR STATISTICAL NORMALITY TESTS IS LIKELY A RESULT OF POOR POWER IN ASSYMETRICAL DISTRIBUTIONS.


THERE ARE A FEW WAYS TO CORRECT FOR HETEROSKEDASTICITY
1. ROBUST STANDARD ERRORS
2. LOGARITHMS!
3. HIGHER ORDER TERMS
4. INTERACTIONS BETWEEN X-VARIABLES

IT IS COMMON TO TRY DIFFERENT MODEL SPECIFICATIONS AND SEE WHAT MAKES SENSE.  EVERYTHING SHOULD BE JUSTIFIED.
IN THIS CASE WE WILL USE ROBUST STANDARD ERRORS

WE HAVE A BASIC REGRESSION PREPARED, BUT WE ARE STIL LACKING SOME KEY CONTROL VARIABLES, LIKE THE NUMBER OF ADULTS IN THE HH, SEX OF THE INDIVIDUAL, MARITAL STATUS AND EDUCATIONAL ATTAINMENT.
*/

gen female=(sex==2)
gen disability= (disabwrk==2)
*HERE WE GENERATED TWO DUMMIES: 1 FOR FEMALES AND 1 FOR INDIVIDUALS WITH A WORK DISABILITY

reg inctot age i.race_cat i.sector i.edu_cat disability female i.marst adultsinhh if employed==1 & income_flag==0, vce(robust)


/*
WE FEEL SATISFIED WITH CATEGORICAL VARIABLES WE'VE INCLUDED, BUT WE ALSO WANT TO TRY SOME DIFFERENT FUNCTIONAL FORMS OF "AGE".
IN THIS CASE, WE GENERATE AGE2 TO INCLUDE A QUADRATIC FORM OF THE VARIABLE
THIS IS PROBABLY MORE REALISTIC THAN HAVING A LINEAR SPECIFICATION.
*/

gen age2= age^2

reg inctot age age2 i.race_cat i.sector i.edu_cat disability female i.marst adultsinhh if employed==1 & income_flag==0, robust

vif

/*
NOTICE THAT I INCLUDE AGE AND AGE^2.  THIS IS A MUST IF YOU ARE INTERESTED IN QUADRATIC RELATIONSHIPS.
THE COEFFICIENTS INDICATE THAT AGE'S EFFECT ON INCOME IS NON LINEAR AND DECREASES AT SOME POINT, BUT WHEN EXACTLY?
*/


*WHEN WE DIFFERENTIATE (BASED ON THE COEFFICIENTS OF THE OUTPUT) AND SOLVE FOR THE TURNING POINT WE GET: 52.94 YEARS OLD.
*AFTER THIS AGE, INCOME BECOMES NEGATIVELY ASSOCIATED WITH Y.

twoway qfit inctot age

*NOTE THAT THE TURNING POINT IN THIS GRAPH IS NOT THE SAME AS WHAT YOU WOULD GET BY CALCULATING IT BY HAND.
*THIS GRAPH DOES NOT USE THE COEFFICIENTS WHEN CONTROLLING FOR ALL OTHER VARIABLES.
*BUT IT AT LEAST GIVES YOU A ROUGH IDEA OF WHERE THE CHANGE IN DIRECTION MIGHT BE.

*IF WE WANT AN EVEN BETTER SPECIFICATION OF FUNCTIONAL FORM, WE CAN SIMPLY USE DUMMIES.
*NOTE THAT THIS CAN ALSO BE DONE AS BEFORE WITH A CATEGORICAL VARIABLE
*WHEN WE INCLUDE ONLY DUMMIES IN THE MODEL FOR AGE, WE HAVE A "FULLY FLEXIBLE" FUNCTIONAL FORM.

gen age18to24= (age>=18 & age<26)
gen age26to35= (age>=26 & age<36)
gen age36to45= (age>=36 & age<46)
gen age46to55= (age>=46 & age<56)
gen age56to65= (age>=56 & age<66)

reg inctot age18to24 age26to35 age36to45 age46to55 age56to65 i.race_cat i.sector i.edu_cat disability female i.marst adultsinhh if employed==1 & income_flag==0, robust
*WHEN USING CATEGORICAL VARIABLES IT IS ALSO IMPORTANT TO KNOW WHETHER THE ESTIMATES FOR THE CATEGORIES ARE STATISITICALLY DIFFERENT FROM ONE ANOTHER
*IN THIS CASE WE COULD USE AN F-TEST
*HERE WE TEST WHETHER THE ESTIMATE FOR AFRICAN AMERICAN IS STATISTICALLY DIFFERENT THAN NATIVE AMERICAN
test 2.race_cat==3.race_cat

*DIVORCED VS SEPARATED
codebook marst
test 2.marst==3.marst

test 3.marst==4.marst

/*
YOU WILL NOTICE THAT ONE OF THE AGE DUMMIES HAS BEEN OMITTED FROM THE REGRESSION.  
THIS IS BECAUSE OF PERFECT COLLINEARITY.
WHEN INCLUDING DUMMIES IN A REGRESSION, THEY MUST BE MUTUALLY EXCLUSIVE 
(I.E. ONE INDIVIDUAL CANNOT BE INCLUDED IN TWO DUMMIES OF THE SAME VARIABLE) 
AND YOU CAN ONLY INCLUDE N-1 DUMMIES.
THE OMITTED DUMMY VARIABLE WILL ALWAYS BE YOUR REFERENCE CATEGORY, AND ALL OF YOUR 
INTERPRETATION SHOULD BE IN THE CONTEXT OF THAT REFERENCE CATEGORY.
SO, IF AGE18TO24 IS OMITTED, THEN ALL COEFFICIENTS FOR THE AGE DUMMIES ARE 
INTERPRETTED AS: INDIVIDUALS AGE 26 TO 35 EARN [BETA] DOLLARS MORE IN TOTAL INCOME THAN THOSE AGE 18 TO 24, ETC.

HOW CAN WE INTERPRET THESE COEFFICIENTS?  IT MAY SEEM DAUNTING WITH SO MANY CATEGORIES 
AND CONTINUOUS VARIABLES PRESENT, BUT IT IS ACTUALLY QUITE EASY.
IF WE TAKE THE COEFFICIENT FOR RACE==2, FOR EXAMPLE, WE INTERPRET IT AS FOLLOWS:
BLACK INDIVIDUALS EARN $2627.226 LESS THAN WHITE INDIVIDUALS, 
WHEN CONTROLLING FOR AGE, SECTOR OF EMPLOYMENT, EDUCATIONAL ATTAINMENT, SEX, 
MARITAL STATUS & THE NUMBER OF ADULTS IN THE HOUSEHOLD.
*/


}








************INTERACTION TERMS*********
{
*IT MAY ALSO BE OF INTEREST TO LOOK AT HOW VARIABLES INTERACT WITH ONE ANOTHER.
*IN THIS CASE, WE WANT TO SEE HOW WOMEN COMPARE TO MEN AND TO EACH OTHER ACROSS AND WITHIN RACIAL GROUPS. 

/*
INTERACTION TERMS ARE MULTIPLICATIVE TERMS AND CAN BE DEFINED MANUALLY BY MAKING NEW VARIABLES, BUT STATA ALSO HAS A BUILT-IN COMMAND
FOR RUNNING INTERACTIONS. 
# BETWEEN TWO VARIABLES WILL GIVE ONLY THE INTERACTION TERM
## BETWEEN TWO VARIABLES WILL GIVE BOTH THE INTERACTION TERMS AND THE RESPECTIVE BASE EFFECTS (SO YOU DON'T HAVE TO INCLUDE THEM SEPARATELY).

THE REGRESSION BELOW CAN ALSO BE RUN AS (IN OLDER VERSIONS OF STATA:
xi: reg  inctot age26to35 age36to45 age46to55 age56to65 i.sector i.edu_cat disability i.marst adultsinhh i.race_cat*female if employed==1 & income_flag==0, robust
*/

*DUMMY-CATEGORICAL INTERACTION
reg inctot age26to35 age36to45 age46to55 age56to65 i.sector i.edu_cat disability i.marst adultsinhh i.race_cat##i.female if employed==1 & income_flag==0, robust baselevels


*DUMMY-CONTINUOUS INTERACTION WITH SHARED INTERCEPT
gen femage= female*age
br female age femage
reg inctot age femage
*THIS ASSUMPTION IS VERY DIFFICULT TO SUPPORT, SO IT IS NOT COMMONLY DONE THIS WAY

*DUMMY-CONTINUOUS INTERACTION WITH UNIQUE INTERCEPTS
reg inctot age i.female femage
*THIS CAN ALSO BE WRITTEN AS (:
reg inctot i.female##c.age
*OR
reg inctot age i.female i.female#c.age
*NOTE THAT CONTINUOUS VARIABLES IN INTERACTIONS NEED TO BE PREFIXED WITH c.


*DUMMY-QUADRATIC INTERACTION WITH SHARED INTERCEPT
gen femage2=female*age2
reg inctot age age2 femage femage2
*THIS ASSUMPTION IS VERY DIFFICULT TO SUPPORT, SO IT IS NOT COMMONLY DONE THIS WAY

*DUMMY-QUADRATIC INTERACTION WITH UNIQUE INTERCEPTS
reg inctot age age2 female femage femage2
}












log close
cmdlog close








/*
GOOD SUPPORTING MATERIAL:
https://stats.idre.ucla.edu/stata/webbooks/reg/
*/
